# Configuration du système de logging

# Configuration générale
version: 1
disable_existing_loggers: false

# Formatters
formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(module)s - %(funcName)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

# Handlers
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/gestionlogs.log
    mode: a
    encoding: utf-8

# Loggers
loggers:
  gestionlogs:
    level: DEBUG
    handlers: [console, file]
    propagate: false

# Logger racine
root:
  level: WARNING
  handlers: [console]
